#!/usr/bin/env bash
# Vérifie que le script est exécuté en tant que root

# Sauvegarde du fichier hosts actuel
cp /etc/hosts /etc/hosts.bak

grep -v -E 'localhost|facebook.com' /etc/hosts.bak > /etc/hosts
# Supprime les lignes existantes pour localhost et facebook.com (si elles existent)
echo -e "127.0.0.2\tlocalhost" >> /etc/hosts
echo -e "8.8.8.8\tfacebook.com" >> /etc/hosts

# Ajoute les nouvelles lignes
echo "Update /etc/hosts"
cat /etc/hosts
